client: improvements to error handling and test_client script

diff --git a/scripts/test_client b/scripts/test_client
--- a/scripts/test_client
+++ b/scripts/test_client
@@ -26,15 +26,26 @@ zecale register --key vk.json --name ${APP_NAME} || echo Already registered
 ( zecale register --key vk.json --name ${APP_NAME} ) && \
     (echo Expected duplicate registration to fail; exit 1)
 
-# Send 4 transactions
+# Send 4 transactions (enough for 2 batches)
 
 zecale submit --name ${APP_NAME} --tx extproof1.json
 zecale submit --name ${APP_NAME} --tx extproof2.json
 zecale submit --name ${APP_NAME} --tx extproof3.json
 zecale submit --name ${APP_NAME} --tx extproof4.json
 
-# Request and aggregate proof
+# Request aggregate proofs. Assuming the server was empty at the beginning of
+# the test, the first two request should succeed, and the third should fail.
 
 zecale get-batch --name ${APP_NAME} --batch-file batch1.json
+zecale get-batch --name ${APP_NAME} --batch-file batch2.json
+zecale get-batch --name ${APP_NAME} --batch-file batch3.json && \
+    (echo Expected failure when no batch available; exit 1)
 
 popd # _test_client_data
+
+set +e
+set +x
+
+echo "=================================================="
+echo "==              Client Test Passed              =="
+echo "=================================================="
